In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
X = np.array([-7,2,-3,-11,14,6,8])

In [4]:
categories = pd.cut(X,4)
categories

[(-11.025, -4.75], (1.5, 7.75], (-4.75, 1.5], (-11.025, -4.75], (7.75, 14.0], (1.5, 7.75], (7.75, 14.0]]
Categories (4, interval[float64]): [(-11.025, -4.75] < (-4.75, 1.5] < (1.5, 7.75] < (7.75, 14.0]]

In [6]:
categories.categories # Includes -4.75 in the first bin and does not -11.025

IntervalIndex([(-11.025, -4.75], (-4.75, 1.5], (1.5, 7.75], (7.75, 14.0]],
              closed='right',
              dtype='interval[float64]')

In [7]:
categories.codes

array([0, 2, 1, 0, 3, 2, 3], dtype=int8)

In [8]:
categories.ordered

True

In [9]:
pd.cut(X,4,retbins=True)

([(-11.025, -4.75], (1.5, 7.75], (-4.75, 1.5], (-11.025, -4.75], (7.75, 14.0], (1.5, 7.75], (7.75, 14.0]]
 Categories (4, interval[float64]): [(-11.025, -4.75] < (-4.75, 1.5] < (1.5, 7.75] < (7.75, 14.0]],
 array([-11.025,  -4.75 ,   1.5  ,   7.75 ,  14.   ]))

In [10]:
marks = np.array([70, 20, 30, 99, 40, 16, 80])

In [11]:
categories, bins = pd.cut(marks, 4, retbins=True, labels=['poor', 'average', 'good', 'excellent'])

In [12]:
categories

[good, poor, poor, excellent, average, poor, excellent]
Categories (4, object): [poor < average < good < excellent]

### Using sklearn KBinsDiscretizer

In [15]:
from sklearn.preprocessing import KBinsDiscretizer

In [18]:
marks = [[70], [20], [30], [99], [40], [16], [80]]
marks

[[70], [20], [30], [99], [40], [16], [80]]

In [19]:
enc = KBinsDiscretizer(n_bins=4, encode='ordinal', strategy='uniform')

In [20]:
enc

KBinsDiscretizer(encode='ordinal', n_bins=4, strategy='uniform')

In [21]:
enc.fit(marks)

KBinsDiscretizer(encode='ordinal', n_bins=4, strategy='uniform')

In [22]:
enc.transform(marks)

array([[2.],
       [0.],
       [0.],
       [3.],
       [1.],
       [0.],
       [3.]])

In [23]:
enc.bin_edges_

array([array([16.  , 36.75, 57.5 , 78.25, 99.  ])], dtype=object)