### To display how numpy arrays are faster then the build in sequences like list

In [27]:
import numpy as np
numpy_array = np.arange(1000000)
default_list = list(range(1000000))

In [28]:
%time for _ in range(10): numpy_array *= 2 

Wall time: 10 ms


In [29]:
%time for _ in range(10): my_list2 = [i * 2 for i in default_list]

Wall time: 1.4 s


### Numpy array capability to perform mathematical operation on arrays just like it is performed on the scalar elements

In [37]:
import numpy as np
data = np.random.randn(2,3)
data

array([[-0.40958057, -0.60819736,  0.18433246],
       [ 0.20185207, -0.54729214,  0.65025417]])

In [38]:
data * 10

array([[-4.09580568, -6.08197355,  1.84332458],
       [ 2.01852071, -5.47292142,  6.5025417 ]])

In [39]:
data + data

array([[-0.81916114, -1.21639471,  0.36866492],
       [ 0.40370414, -1.09458428,  1.30050834]])

### Methods offered to display the properties of an array

In [40]:
data.shape # Tuple displaying the size of each dimention

(2, 3)

In [41]:
data.dtype # Displays the data type

dtype('float64')

### Creating ndarray

In [48]:
# Accepts any sequence like object
# 1d Array
my_list = list(range(10))
my_array = np.array(my_list)
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
print(my_array.shape); print(my_array.dtype); print(my_array.ndim)

(10,)
int32
1


In [56]:
# 2d Arrays
data2 = [[1,2,3], [4,5,6]]
array2 = np.array(data2)
print(array2)
print(array2.shape)
print(array2.dtype)
print(array2.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
int32
2


In [57]:
# Using zeros and ones Functions
data3 = np.zeros(10)
data4 = np.zeros((2,3))
print(data3); print(data3.shape); print(data3.ndim); print(data3.dtype)
print('--------------------------------')
print(data4); print(data4.shape); print(data4.ndim); print(data4.dtype)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
(10,)
1
float64
--------------------------------
[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)
2
float64


In [58]:
# Using zeros and ones Functions
data5 = np.ones(10)
data6 = np.ones((2,3))
print(data5); print(data5.shape); print(data5.ndim); print(data5.dtype)
print('--------------------------------')
print(data6); print(data6.shape); print(data6.ndim); print(data6.dtype)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
(10,)
1
float64
--------------------------------
[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)
2
float64


In [62]:
# Using empty function
# Creates an empty array without initializing its value to any particular value so it an be anything
np.empty((3,3,2))

array([[[4.45057637e-308, 9.34604358e-307],
        [9.34605037e-307, 1.11260483e-306],
        [1.78019354e-306, 4.45066125e-308]],

       [[9.34605037e-307, 1.60220393e-306],
        [1.24611674e-306, 4.45057637e-308],
        [9.34597567e-307, 2.22523004e-306]],

       [[2.13620264e-306, 4.45063578e-308],
        [1.37961302e-306, 8.45596650e-307],
        [5.73116149e-322, 2.22507386e-306]]])

In [64]:
# Using full function
# Creates a 2 by 3 array with all the values 2
np.full((2,3),2)

array([[2, 2, 2],
       [2, 2, 2]])

In [78]:
# Using arange that is similar to range function
print(np.arange(3))
print(np.arange(1,3))
print(np.arange(1,11,2))

[0 1 2]
[1 2]
[1 3 5 7 9]


In [86]:
# Generates a N * N matrix (1s on the diagonal and 0s elsewhere) # eye or identity can use anything
np.identity(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])