### To display how numpy arrays are faster then the build in sequences like list

In [24]:
import numpy as np
numpy_array = np.arange(1000000)
default_list = list(range(1000000))

In [25]:
%time for _ in range(10): numpy_array *= 2 

Wall time: 6.98 ms


In [26]:
%time for _ in range(10): my_list2 = [i * 2 for i in default_list]

Wall time: 1.32 s


### Numpy array capability to perform mathematical operation on arrays just like it is performed on the scalar elements

In [27]:
import numpy as np
data = np.random.randn(2,3)
data

array([[-0.02950055,  1.00027451, -0.55265034],
       [-0.17637158,  0.46681051, -0.83387996]])

In [28]:
data * 10

array([[-0.29500547, 10.00274507, -5.52650338],
       [-1.76371579,  4.66810511, -8.33879959]])

In [29]:
data + data

array([[-0.05900109,  2.00054901, -1.10530068],
       [-0.35274316,  0.93362102, -1.66775992]])

### Methods offered to display the properties of an array

In [30]:
data.shape # Tuple displaying the size of each dimention

(2, 3)

In [31]:
data.dtype # Displays the data type

dtype('float64')

### Creating ndarray

In [32]:
# Accepts any sequence like object
# 1d Array
my_list = list(range(10))
my_array = np.array(my_list)
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
print(my_array.shape); print(my_array.dtype); print(my_array.ndim)

(10,)
int32
1


In [34]:
# 2d Arrays
data2 = [[1,2,3], [4,5,6]]
array2 = np.array(data2)
print(array2)
print(array2.shape)
print(array2.dtype)
print(array2.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
int32
2


In [35]:
# Using zeros and ones Functions
data3 = np.zeros(10)
data4 = np.zeros((2,3))
print(data3); print(data3.shape); print(data3.ndim); print(data3.dtype)
print('--------------------------------')
print(data4); print(data4.shape); print(data4.ndim); print(data4.dtype)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
(10,)
1
float64
--------------------------------
[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)
2
float64


In [36]:
# Using zeros and ones Functions
data5 = np.ones(10)
data6 = np.ones((2,3))
print(data5); print(data5.shape); print(data5.ndim); print(data5.dtype)
print('--------------------------------')
print(data6); print(data6.shape); print(data6.ndim); print(data6.dtype)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
(10,)
1
float64
--------------------------------
[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)
2
float64


In [37]:
# Using empty function
# Creates an empty array without initializing its value to any particular value so it an be anything
np.empty((3,3,2))

array([[[3.56043053e-307, 1.60219306e-306],
        [2.44763557e-307, 1.69119330e-306],
        [1.33514617e-307, 3.33776697e-307]],

       [[2.78145776e-307, 1.37959129e-306],
        [1.60220393e-306, 1.37961709e-306],
        [1.06808978e-306, 6.23050559e-307]],

       [[1.29061685e-306, 1.24610383e-306],
        [1.78020169e-306, 1.78020984e-306],
        [8.34454050e-308, 2.29179042e-312]]])

In [38]:
# Using full function
# Creates a 2 by 3 array with all the values 2
np.full((2,3),2)

array([[2, 2, 2],
       [2, 2, 2]])

In [39]:
# Using arange that is similar to range function
print(np.arange(3))
print(np.arange(1,3))
print(np.arange(1,11,2))

[0 1 2]
[1 2]
[1 3 5 7 9]


In [40]:
# Generates a N * N matrix (1s on the diagonal and 0s elsewhere) # eye or identity can use anything
np.identity(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [41]:
# Explore other functions like ones_like, zeros_like, empty_like, full_like

### Data types for ndarray

- The data type or dtype is a special object containing the information (or metadata, data about data) the ndarray needs to interpret a chunk of memory as a particular type of data

In [42]:
arr1 = np.array([1, 2, 3, 4, 5], dtype = np.float64)
arr1

array([1., 2., 3., 4., 5.])

In [43]:
arr2 = np.array([1.3,2.6,3.2], dtype = np.int32)
arr2 # Truncates the decimal places

array([1, 2, 3])

- You can explicitly convert or cast an array from one dtype to another using ndarray’s astype method
- Calling astype always creates a new array (a copy of the data), even if the new dtype is the same as the old dtype

In [44]:
arr1 = arr1.astype(np.int8) # Casting float64 to int8
arr1.dtype

dtype('int8')

In [45]:
arr3 = np.array(['1.32', '1.1', '10.2'], dtype = np.string_)
arr3.dtype

dtype('S4')

In [46]:
# will give ValueError as str(1.32) can not be converted into int. First cast the float and then int.
arr3 = arr3.astype(np.int32) 
arr3

ValueError: invalid literal for int() with base 10: '1.32'

In [47]:
arr3 = arr3.astype(np.float32)
arr3

array([ 1.32,  1.1 , 10.2 ], dtype=float32)

### Arithmetic with NumPy Arrays

In [48]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [49]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [50]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [51]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [52]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [53]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [54]:
arr2 > arr # Element wise comparisons

array([[False,  True, False],
       [ True, False,  True]])

### Basic Indexing and Slicing

In [55]:
# 1d array indexing acts just like lists
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
arr[5] # element at 5th index

5

In [57]:
arr[5:8] # elements between 5 and 8 where 8 is not inclusive

array([5, 6, 7])

In [58]:
# first difference with the list. Will give TypeError if we try the same thing with lists. 
arr[5:8] = 12 # will assign 12 value to elements at index 5, 6 and 7 
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [59]:
arr[:3] # first 3 element

array([0, 1, 2])

In [60]:
arr[-3:] # last 3 elements

array([12,  8,  9])

In [61]:
lista = [0,1,2,3,4]
lista

[0, 1, 2, 3, 4]

In [62]:
lista [5:8] = 12 # to fix this write lista[5:8] = 12,12,12

TypeError: can only assign an iterable

- Arrays are basically views on original data. 
- As NumPy has been designed to be able to work with very large arrays, you could imagine performance and memory problems if NumPy insisted on always copying data.

In [63]:
arr1 = np.arange(10)
new_slice = arr1[5:8]
new_slice[:] = 12
arr1

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [64]:
# to copy use .copy()
arr2 = np.arange(10)
new_slice = arr2[5:8].copy()
new_slice[:] = 64
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- In an n dimentional array element at each index is an (n-1) dimentional array itself
- For example in a 2d array, the element at each index is a 1d array

In [65]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
arr2d[2]

array([7, 8, 9])

In [67]:
arr2d[0][2]  # Returns first row, 3rd element i.e. 3. Can also use arr2d[0,2]

3

In [68]:
arr3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [69]:
arr3d[0].shape # Returns 2*3 array

(2, 3)

In [70]:
# Both scalar values and arrays can be assigned to arr3d[0]
backup_old_values = arr3d[0].copy()
arr3d[0] = 12
arr3d

array([[[12, 12, 12],
        [12, 12, 12]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [71]:
# Restoring back the values
arr3d[0] = backup_old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

#### Indexing with slices

In [72]:
arr1d = np.arange(100,111)
arr1d

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [73]:
arr1d[1:6] # Elements with index 1 till 5

array([101, 102, 103, 104, 105])

In [78]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
arr2d[:2] # can be read as selecting the first two rows of arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [81]:
arr2d[:2,1:] # first 2 rows and 2nd column onwards

array([[2, 3],
       [5, 6]])

In [82]:
# Select 2nd row and first two columns
arr2d[1,:2]

array([4, 5])

In [84]:
# first two rows and 3rd column
arr2d[:2,2]

array([3, 6])

In [85]:
# first column only i.e all rows but only first column
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [86]:
# Can so assignment as well
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### Boolean Indexing

In [88]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7,4)
data

array([[ 0.35031513,  1.06566272, -0.97435161,  1.00530732],
       [ 0.50564296,  1.69773929, -1.21898843,  1.50886595],
       [ 0.64715488, -0.63883129, -0.82876123, -0.35169849],
       [ 0.26897086, -0.43378273, -0.43541459, -0.29612085],
       [ 1.57345863,  0.27462365, -0.61390918,  0.32126883],
       [ 0.85636133, -0.85162581,  0.22234283,  0.15579061],
       [-1.58640177, -0.57072598,  0.13517321, -2.53140045]])

In [91]:
# Suppose each name represents each row and we want to print rows which represents Bob i.e. Row 1st and 4th
# Note: The boolean array must be of the same length as the array axis it’s indexing
print(names == 'Bob')
data[names == 'Bob']

[ True False False  True False False False]


array([[ 0.35031513,  1.06566272, -0.97435161,  1.00530732],
       [ 0.26897086, -0.43378273, -0.43541459, -0.29612085]])

In [94]:
# Select rows with Joe and 3rd and 4th column
data[names == 'Joe', 2:]

array([[-1.21898843,  1.50886595],
       [ 0.22234283,  0.15579061],
       [ 0.13517321, -2.53140045]])

In [95]:
# Select everything but Bob
# Method 1
data[names != 'Bob']

array([[ 0.50564296,  1.69773929, -1.21898843,  1.50886595],
       [ 0.64715488, -0.63883129, -0.82876123, -0.35169849],
       [ 1.57345863,  0.27462365, -0.61390918,  0.32126883],
       [ 0.85636133, -0.85162581,  0.22234283,  0.15579061],
       [-1.58640177, -0.57072598,  0.13517321, -2.53140045]])

In [98]:
# Method2
data[~ (names == 'Bob')]

array([[ 0.50564296,  1.69773929, -1.21898843,  1.50886595],
       [ 0.64715488, -0.63883129, -0.82876123, -0.35169849],
       [ 1.57345863,  0.27462365, -0.61390918,  0.32126883],
       [ 0.85636133, -0.85162581,  0.22234283,  0.15579061],
       [-1.58640177, -0.57072598,  0.13517321, -2.53140045]])

In [102]:
# Select names with Bob and Will
# can use AND (&) OR (|) Operators as well
condition = (names == 'Bob') | (names == 'Will')
data[condition]

array([[ 0.35031513,  1.06566272, -0.97435161,  1.00530732],
       [ 0.64715488, -0.63883129, -0.82876123, -0.35169849],
       [ 0.26897086, -0.43378273, -0.43541459, -0.29612085],
       [ 1.57345863,  0.27462365, -0.61390918,  0.32126883]])

In [104]:
# Selecting all negative values and setting it to 0
data[data < 0] = 0

In [105]:
data

array([[0.35031513, 1.06566272, 0.        , 1.00530732],
       [0.50564296, 1.69773929, 0.        , 1.50886595],
       [0.64715488, 0.        , 0.        , 0.        ],
       [0.26897086, 0.        , 0.        , 0.        ],
       [1.57345863, 0.27462365, 0.        , 0.32126883],
       [0.85636133, 0.        , 0.22234283, 0.15579061],
       [0.        , 0.        , 0.13517321, 0.        ]])

### Fancy Indexing
- Fancy indexing is a term adopted by NumPy to describe indexing using integer arrays.

In [106]:
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [107]:
# Pass index of the rows that you want to select in a list object
arr[[4,3,0]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.]])

In [108]:
# Same goes with negative indexing
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [110]:
# 2d array
arr2d = np.arange(32).reshape((8,4))
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [113]:
arr2d[[1, 5, 7, 2], [0, 3, 1, 2]] # Rows and columns

array([ 4, 23, 29, 10])

### Transposing Arrays and Swapping Axes

In [114]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [115]:
arr.T # Swaps axis 0 with axis 1

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [116]:
arr = np.ones((6,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [117]:
# Transpose normally used while calculating the dot product
np.dot(arr.T, arr)

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [122]:
# For higher dimentions, transpose will accept a tuple of axis to perform swapping
arr3d = np.arange(24).reshape((2,3,4))
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [124]:
arr3d.transpose((1,0,2)).shape # Explore swapaxes function

(3, 2, 4)

### Universal Functions: Fast Element-Wise Array Functions
- A universal function, or ufunc, is a function that performs element-wise operations on data in ndarrays.
    - unary ufunc like sqrt, exp which takes one input
    - binary ufunc like add, maximum which takes two inputs

#### Unary universal functions

In [125]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:

np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [128]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [141]:
arr = np.random.randn(10) * 5
print(arr)
decimal_part, integer_part = np.modf(arr) # Returns integer and fractional part
print(decimal_part)
print(integer_part)

[-2.00758303 -1.3019268   6.67897731 -6.06507374  9.70124357 -3.33201104
  5.1632555   0.90960315 -0.76732714 -7.65489456]
[-0.00758303 -0.3019268   0.67897731 -0.06507374  0.70124357 -0.33201104
  0.1632555   0.90960315 -0.76732714 -0.65489456]
[-2. -1.  6. -6.  9. -3.  5.  0. -0. -7.]


In [148]:
# Ufuncs accept an optional out argument that allows them to operate in-place on arrays
arr = np.random.randn(7) * 5
np.sqrt(arr, arr) # Will act as arr = np.sqrt(arr)
arr

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in sqrt
  This is separate from the ipykernel package so we can avoid doing imports until


array([       nan, 1.01321698,        nan,        nan, 1.29319776,
       1.16997164, 1.66537037])

#### Binary Universal functions

In [130]:
np.add(arr,2)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [132]:
np.add(arr,arr)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [133]:
arr1 = np.random.randn(5)
arr1

array([-1.37236731, -1.4010573 ,  0.01569497, -0.1062807 ,  0.08853387])

In [134]:
arr2 = np.random.randn(5)
arr2

array([ 0.38436878,  0.50226211,  0.0567446 , -1.13646225,  0.79393864])

In [135]:
np.maximum(arr1,arr2)

array([ 0.38436878,  0.50226211,  0.0567446 , -0.1062807 ,  0.79393864])