### To display how numpy arrays are faster then the build in sequences like list

In [27]:
import numpy as np
numpy_array = np.arange(1000000)
default_list = list(range(1000000))

In [28]:
%time for _ in range(10): numpy_array *= 2 

Wall time: 10 ms


In [29]:
%time for _ in range(10): my_list2 = [i * 2 for i in default_list]

Wall time: 1.4 s


### Numpy array capability to perform mathematical operation on arrays just like it is performed on the scalar elements

In [37]:
import numpy as np
data = np.random.randn(2,3)
data

array([[-0.40958057, -0.60819736,  0.18433246],
       [ 0.20185207, -0.54729214,  0.65025417]])

In [38]:
data * 10

array([[-4.09580568, -6.08197355,  1.84332458],
       [ 2.01852071, -5.47292142,  6.5025417 ]])

In [39]:
data + data

array([[-0.81916114, -1.21639471,  0.36866492],
       [ 0.40370414, -1.09458428,  1.30050834]])

### Methods offered to display the properties of an array

In [40]:
data.shape # Tuple displaying the size of each dimention

(2, 3)

In [41]:
data.dtype # Displays the data type

dtype('float64')

### Creating ndarray

In [48]:
# Accepts any sequence like object
# 1d Array
my_list = list(range(10))
my_array = np.array(my_list)
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
print(my_array.shape); print(my_array.dtype); print(my_array.ndim)

(10,)
int32
1


In [56]:
# 2d Arrays
data2 = [[1,2,3], [4,5,6]]
array2 = np.array(data2)
print(array2)
print(array2.shape)
print(array2.dtype)
print(array2.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
int32
2


In [57]:
# Using zeros and ones Functions
data3 = np.zeros(10)
data4 = np.zeros((2,3))
print(data3); print(data3.shape); print(data3.ndim); print(data3.dtype)
print('--------------------------------')
print(data4); print(data4.shape); print(data4.ndim); print(data4.dtype)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
(10,)
1
float64
--------------------------------
[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)
2
float64


In [58]:
# Using zeros and ones Functions
data5 = np.ones(10)
data6 = np.ones((2,3))
print(data5); print(data5.shape); print(data5.ndim); print(data5.dtype)
print('--------------------------------')
print(data6); print(data6.shape); print(data6.ndim); print(data6.dtype)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
(10,)
1
float64
--------------------------------
[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)
2
float64


In [62]:
# Using empty function
# Creates an empty array without initializing its value to any particular value so it an be anything
np.empty((3,3,2))

array([[[4.45057637e-308, 9.34604358e-307],
        [9.34605037e-307, 1.11260483e-306],
        [1.78019354e-306, 4.45066125e-308]],

       [[9.34605037e-307, 1.60220393e-306],
        [1.24611674e-306, 4.45057637e-308],
        [9.34597567e-307, 2.22523004e-306]],

       [[2.13620264e-306, 4.45063578e-308],
        [1.37961302e-306, 8.45596650e-307],
        [5.73116149e-322, 2.22507386e-306]]])

In [64]:
# Using full function
# Creates a 2 by 3 array with all the values 2
np.full((2,3),2)

array([[2, 2, 2],
       [2, 2, 2]])

In [78]:
# Using arange that is similar to range function
print(np.arange(3))
print(np.arange(1,3))
print(np.arange(1,11,2))

[0 1 2]
[1 2]
[1 3 5 7 9]


In [86]:
# Generates a N * N matrix (1s on the diagonal and 0s elsewhere) # eye or identity can use anything
np.identity(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [1]:
# Explore other functions like ones_like, zeros_like, empty_like, full_like

### Data types for ndarray

- The data type or dtype is a special object containing the information (or metadata, data about data) the ndarray needs to interpret a chunk of memory as a particular type of data

In [6]:
arr1 = np.array([1, 2, 3, 4, 5], dtype = np.float64)
arr1

array([1., 2., 3., 4., 5.])

In [10]:
arr2 = np.array([1.3,2.6,3.2], dtype = np.int32)
arr2 # Truncates the decimal places

array([1, 2, 3])

- You can explicitly convert or cast an array from one dtype to another using ndarray’s astype method
- Calling astype always creates a new array (a copy of the data), even if the new dtype is the same as the old dtype

In [29]:
arr1 = arr1.astype(np.int8) # Casting float64 to int8
arr1.dtype

dtype('int8')

In [30]:
arr3 = np.array(['1.32', '1.1', '10.2'], dtype = np.string_)
arr3.dtype

dtype('S4')

In [31]:
# will give ValueError as str(1.32) can not be converted into int. First cast the float and then int.
arr3 = arr3.astype(np.int32) 
arr3

ValueError: invalid literal for int() with base 10: '1.32'

In [32]:
arr3 = arr3.astype(np.float32)
arr3

array([ 1.32,  1.1 , 10.2 ], dtype=float32)

### Arithmetic with NumPy Arrays

In [33]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [34]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [35]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [36]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [37]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [38]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [39]:
arr2 > arr # Element wise comparisons

array([[False,  True, False],
       [ True, False,  True]])

### Basic Indexing and Slicing

In [44]:
# 1d array indexing acts just like lists
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
arr[5] # element at 5th index

5

In [46]:
arr[5:8] # elements between 5 and 8 where 8 is not inclusive

array([5, 6, 7])

In [47]:
# first difference with the list. Will give TypeError if we try the same thing with lists. 
arr[5:8] = 12 # will assign 12 value to elements at index 5, 6 and 7 
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [48]:
arr[:3] # first 3 element

array([0, 1, 2])

In [49]:
arr[-3:] # last 3 elements

array([12,  8,  9])

In [56]:
lista = [0,1,2,3,4]
lista

[0, 1, 2, 3, 4]

In [59]:
lista [5:8] = 12 # to fix this write lista[5:8] = 12,12,12

TypeError: can only assign an iterable

- Arrays are basically views on original data. 
- As NumPy has been designed to be able to work with very large arrays, you could imagine performance and memory problems if NumPy insisted on always copying data.

In [63]:
arr1 = np.arange(10)
new_slice = arr1[5:8]
new_slice[:] = 12
arr1

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [64]:
# to copy use .copy()
arr2 = np.arange(10)
new_slice = arr2[5:8].copy()
new_slice[:] = 64
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- In an n dimentional array element at each index is an (n-1) dimentional array itself
- For example in a 2d array, the element at each index is a 1d array

In [71]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
arr2d[2]

array([7, 8, 9])

In [73]:
arr2d[0][2]  # Returns first row, 3rd element i.e. 3. Can also use arr2d[0,2]

3

In [76]:
arr3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [77]:
arr3d[0].shape # Returns 2*3 array

(2, 3)

In [79]:
# Both scalar values and arrays can be assigned to arr3d[0]
backup_old_values = arr3d[0].copy()
arr3d[0] = 12
arr3d

array([[[12, 12, 12],
        [12, 12, 12]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [80]:
# Restoring back the values
arr3d[0] = backup_old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])