### Numpy Array - Introduction
- Is fast than the build in python data types
- NumPy internally stores data in a contiguous block of memory, independent of other built-in Python objects. NumPy’s library of algorithms written in the C language can operate on this memory without any type checking or other overhead. NumPy arrays also use much less memory than built-in Python sequences
- NumPy operations perform complex computations on entire arrays without the need for Python for loops

In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [3]:
%time for _ in range(10): my_arr = my_arr * 2

Wall time: 34.1 ms


In [4]:
%time for _ in range(10): my_list2 = [ value * 2 for value in my_list]

Wall time: 1.89 s


### The NumPy ndarray: A Multidimensional Array Object
- An ndarray is a generic multidimensional container for homogeneous data; that is, all of the elements must be the same type

In [5]:
data = np.random.randn(2,3)
data

array([[-1.38459675,  0.53011092, -0.4536976 ],
       [ 0.28166035,  0.18727793,  0.71389628]])

In [6]:
data * 10

array([[-13.84596749,   5.30110919,  -4.53697599],
       [  2.81660353,   1.87277932,   7.13896284]])

In [7]:
data + data

array([[-2.7691935 ,  1.06022184, -0.9073952 ],
       [ 0.56332071,  0.37455586,  1.42779257]])

In [8]:
data.shape

(2, 3)

In [9]:
data.dtype

dtype('float64')

#### Creating ndarrays

In [10]:
data1 = [1, 2, 3, 4, 5]
my_arr1 = np.array(data1)
my_arr1

array([1, 2, 3, 4, 5])

In [11]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
my_arr2 = np.array(data2)
my_arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
my_arr2.shape

(2, 4)

In [13]:
my_arr2.ndim

2

In [14]:
my_arr3 = np.zeros(5)
my_arr3

array([0., 0., 0., 0., 0.])

In [15]:
my_arr4 = np.ones(5)
my_arr4

array([1., 1., 1., 1., 1.])

In [16]:
np.empty((2, 2, 3)) # 2d array of 2 * 3. empty may return any garbage values not necessary zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [17]:
# arange is a array version of the build in range function
np.arange(5)

array([0, 1, 2, 3, 4])

In [18]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [19]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [20]:
my_arr5 = np.ones((2,2))
my_arr6 = np.zeros_like(my_arr5) # similarly we have ones_like, empty_like, full_like which copies the shape and makes a new array
my_arr6

array([[0., 0.],
       [0., 0.]])

In [21]:
np.full((2,3), '*') # Passing the shape and fill value

array([['*', '*', '*'],
       ['*', '*', '*']], dtype='<U1')

In [22]:
np.eye(2) # 2 * 2 (1's on the diagonal and 0's elsewhere). identity also does the same thing

array([[1., 0.],
       [0., 1.]])

#### Data Types for ndarrays
- The data type or dtype is a special object containing the information (or metadata, data about data)
- int (8,16,32)
- float (16,32,64,128)
- complex(64, 128, 256)
- bool, object, string_, unicode_

In [23]:
my_arr7 = np.array([1, 2, 3, 4, 5], dtype=np.float64)
my_arr7.dtype

dtype('float64')

In [24]:
my_arr8 = np.array(range(10), dtype=np.int32)
my_arr8.dtype

dtype('int32')

In [25]:
# can also cast dtypes
# Calling astype always creates a new array (a copy of the data), even if the new dtype is the same as the old dtype.
my_arr7 = my_arr7.astype(np.int32)

In [26]:
my_arr7.dtype

dtype('int32')

#### Arithmetic with NumPy Arrays
- Arrays are important because they enable you to express batch operations on data without writing any for loops. NumPy users call this vectorization. Any arithmetic operations between equal-size arrays applies the operation element-wise:
- Operations between differently sized arrays is called broadcasting

In [27]:
my_arr9 = np.random.randn(2,2)

In [28]:
my_arr9

array([[-1.12692979,  0.95327542],
       [-0.03589057,  1.90417927]])

In [29]:
my_arr9 * my_arr9

array([[1.26997075e+00, 9.08734032e-01],
       [1.28813272e-03, 3.62589870e+00]])

In [30]:
my_arr9 - my_arr9

array([[0., 0.],
       [0., 0.]])

In [31]:
my_arr9 + my_arr9

array([[-2.25385958,  1.90655085],
       [-0.07178113,  3.80835855]])

In [32]:
1 / my_arr9

array([[ -0.88736673,   1.04901477],
       [-27.86247519,   0.52516064]])

In [33]:
my_arr9 = my_arr9 ** 2
my_arr9

array([[1.26997075e+00, 9.08734032e-01],
       [1.28813272e-03, 3.62589870e+00]])

In [34]:
my_arr9 ** 0.5

array([[1.12692979, 0.95327542],
       [0.03589057, 1.90417927]])

In [35]:
my_arr10 = np.random.randn(2,2)
my_arr10 > my_arr9

array([[False,  True],
       [ True, False]])

In [36]:
my_arr10

array([[0.86579475, 1.69102571],
       [1.87811237, 1.10156897]])

#### Basic Indexing and Slicing

In [37]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
arr[5]

5

In [39]:
arr[5:8]

array([5, 6, 7])

In [40]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [41]:
arr_slice = arr[5:8] # Does not explicitly copy
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [42]:
arr_copy = arr.copy()
arr_copy

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [43]:
arr_copy[:] = 1 # no effect on original array
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [44]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [45]:
arr2d[0][0]

1

In [46]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [47]:
arr3d[0,0]

array([1, 2, 3])

In [48]:
arr_copy = arr3d.copy()
arr3d[:] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[42, 42, 42],
        [42, 42, 42]]])

In [49]:
arr3d = arr_copy
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

#### Indexing with slices

In [50]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [51]:
arr[:6] # first 6 elements

array([ 0,  1,  2,  3,  4, 64])

In [52]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
arr2d[:2] # first two rows

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
arr2d[:2][:1]

array([[1, 2, 3]])

In [55]:
arr2d[:2, :2] # first two rows then first 2 colunms

array([[1, 2],
       [4, 5]])

#### Boolean Indexing

In [56]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [57]:
data = np.random.randn(7, 4)
data

array([[ 0.53519018, -1.91689134, -1.53097028, -0.13659288],
       [ 0.09061392, -1.27510652,  0.27344922, -1.70952739],
       [-1.79761667,  0.84835127,  0.07404426,  2.05894003],
       [-0.46852151, -1.18057878,  1.66281481, -0.64965551],
       [-0.82633609, -0.60485679, -0.61957853, -1.8669283 ],
       [ 0.42579839,  0.8833831 ,  0.16782196, -0.72680011],
       [-0.54578635, -0.99583069, -0.21867851, -0.2895927 ]])

In [58]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [59]:
data[names == 'Bob']

array([[ 0.53519018, -1.91689134, -1.53097028, -0.13659288],
       [-0.46852151, -1.18057878,  1.66281481, -0.64965551]])

In [60]:
data[names == 'Bob', :2] # then first two columns

array([[ 0.53519018, -1.91689134],
       [-0.46852151, -1.18057878]])

In [61]:
mask = (names=='Bob') | (names == 'Will')
data[~mask]

array([[ 0.09061392, -1.27510652,  0.27344922, -1.70952739],
       [ 0.42579839,  0.8833831 ,  0.16782196, -0.72680011],
       [-0.54578635, -0.99583069, -0.21867851, -0.2895927 ]])

In [62]:
# setting all -ve values to zero
data[data < 0] = 0
data

array([[0.53519018, 0.        , 0.        , 0.        ],
       [0.09061392, 0.        , 0.27344922, 0.        ],
       [0.        , 0.84835127, 0.07404426, 2.05894003],
       [0.        , 0.        , 1.66281481, 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.42579839, 0.8833831 , 0.16782196, 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

#### Fancy Indexing

In [63]:
arr = np.empty((8, 4))

In [64]:
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [65]:
arr[[0,2,5]]

array([[0., 0., 0., 0.],
       [2., 2., 2., 2.],
       [5., 5., 5., 5.]])

In [66]:
arr = np.arange(32).reshape(8,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [67]:
arr[[0,2]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [68]:
arr[[0,2], [0, -1]] #0th list 1st column, 2rd list last column

array([ 0, 11])

#### Transposing Arrays and Swapping Axes

In [69]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [70]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [71]:
ones2d = np.ones((2,3))
ones2d

array([[1., 1., 1.],
       [1., 1., 1.]])

In [72]:
np.dot(ones2d, ones2d.T)

array([[3., 3.],
       [3., 3.]])

In [73]:
arr = np.arange(6).reshape(2,3)
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [74]:
np.dot(arr, arr.T)

array([[ 5, 14],
       [14, 50]])

In [75]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [76]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [77]:
arr.transpose((2,1,0))

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

### Universal Functions: Fast Element-Wise Array Functions

In [78]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [80]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [81]:
np.add(arr, arr)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [82]:
np.multiply(arr,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [83]:
arr[-2:] = 100
arr2 = np.arange(1,11)
np.maximum(arr, arr2) # Return the elementwise maximum value

array([  1,   2,   3,   4,   5,   6,   7,   8, 100, 100])

In [84]:
arr = np.random.randn(7) * 5
arr

array([-4.34516554, -9.69068355,  3.0107283 , -2.0953189 ,  3.71562242,
       -0.60057866,  4.46801002])

In [85]:
remainder, whole_part = np.modf(arr)
remainder, whole_part

(array([-0.34516554, -0.69068355,  0.0107283 , -0.0953189 ,  0.71562242,
        -0.60057866,  0.46801002]),
 array([-4., -9.,  3., -2.,  3., -0.,  4.]))

In [86]:
np.sqrt(arr, arr) # optional 2nd argument as output variable
arr

C:\Users\pankaj\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([       nan,        nan, 1.73514504,        nan, 1.92759498,
              nan, 2.11376678])

In [87]:
my_list = [1.49, 1.5, 1.51, 1.01]
arr = np.array(my_list)
arr

array([1.49, 1.5 , 1.51, 1.01])

In [88]:
np.ceil(arr)

array([2., 2., 2., 2.])

In [89]:
np.floor(arr)

array([1., 1., 1., 1.])

In [90]:
np.isnan(arr)

array([False, False, False, False])

### Array-Oriented Programming with Arrays

In [91]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [92]:
np.where(cond, xarr, yarr) # if True, pull from xarr else yarr

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [93]:
# Replace all +ve values with 2 and negative with -2
arr = np.random.randn(3,3)
arr

array([[ 0.44889987,  1.28277017, -1.8599036 ],
       [ 1.14236282,  0.49212753, -0.36130495],
       [ 0.19473525, -0.04136796, -0.60680435]])

In [94]:
np.where(arr > 0, 2, -2)

array([[ 2,  2, -2],
       [ 2,  2, -2],
       [ 2, -2, -2]])

In [95]:
# Set only +ve values to 0 rest asIS
np.where(arr > 0, 0, arr)

array([[ 0.        ,  0.        , -1.8599036 ],
       [ 0.        ,  0.        , -0.36130495],
       [ 0.        , -0.04136796, -0.60680435]])

#### Mathematical and Statistical Methods

In [96]:
arr = np.random.randn(5,4)
arr

array([[-1.88904249, -1.26347611, -1.86354967,  0.41729005],
       [-0.18535396, -0.36570299,  0.00793899,  0.05402305],
       [-0.11625358,  0.58449748, -0.39471639,  1.19526109],
       [-0.48311834,  0.7271948 ,  2.39628078,  1.19071087],
       [-1.75243699,  0.96375043, -1.2854339 ,  0.9740126 ]])

In [97]:
arr.mean() # Entire Array

-0.05440621403243412

In [98]:
arr.mean(axis=0) # columnwise mean

array([-0.88524107,  0.12925272, -0.22789604,  0.76625953])

In [99]:
arr.mean(axis=1) #rowwise mean

array([-1.14969455, -0.12227373,  0.31719715,  0.95776703, -0.27502697])

In [100]:
arr.std() # Entire array, similarly can be calculated for column and row

1.1266397014361862

In [101]:
np.mean(arr, axis=1) #Alternative way

array([-1.14969455, -0.12227373,  0.31719715,  0.95776703, -0.27502697])

In [102]:
arr.sum()

-1.0881242806486824

In [103]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [104]:
arr.sum(0)

array([ 9, 12, 15])

In [105]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

In [106]:
arr.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [107]:
arr.cumprod()

array([   1,    2,    6,   24,  120,  720, 5040], dtype=int32)

#### Methods for Boolean Arrays

In [108]:
arr = np.random.randn(100)

In [109]:
# number of +ve values
(arr > 0).sum()

47

In [110]:
# number f -ve values
(arr < 0).sum()

53

In [111]:
bools = np.array([False, False, True, False])
bools.any()

True

In [112]:
bools.all()

False

#### Sorting

In [113]:
arr = np.arange(1,11, 1)
arr[[0, 5, 2]] = 77
arr

array([77,  2, 77,  4,  5, 77,  7,  8,  9, 10])

In [114]:
arr.sort()
arr

array([ 2,  4,  5,  7,  8,  9, 10, 77, 77, 77])

In [115]:
arr = np.random.randn(5, 3)
arr

array([[-1.64773578,  0.29048861,  0.6918534 ],
       [-0.36869742, -0.90255537,  1.3654677 ],
       [ 0.6920974 , -0.51658196, -0.09364347],
       [ 0.3876543 ,  0.40179521,  0.20228689],
       [ 0.06797251, -1.58670393, -1.19952997]])

In [116]:
arr.sort(axis=1) # row level sorting
arr

array([[-1.64773578,  0.29048861,  0.6918534 ],
       [-0.90255537, -0.36869742,  1.3654677 ],
       [-0.51658196, -0.09364347,  0.6920974 ],
       [ 0.20228689,  0.3876543 ,  0.40179521],
       [-1.58670393, -1.19952997,  0.06797251]])

#### Unique and Other Set Logic

In [117]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [118]:
np.unique(names) # Returns sorted and unique value of names. Original array will remain intact

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [119]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

array([1, 2, 3, 4])

In [120]:
# unique is alternative to the below code
sorted(set(names))

['Bob', 'Joe', 'Will']

In [121]:
x = np.array([6, 0, 0, 3, 2, 5, 6])
y = [2, 3, 6, -1]
np.in1d(x,y ) # meaning = x in y

array([ True, False, False,  True,  True, False,  True])

In [122]:
np.intersect1d(x, y)

array([2, 3, 6])

In [123]:
np.union1d(x,y)

array([-1,  0,  2,  3,  5,  6])

In [124]:
np.setdiff1d(x,y)

array([0, 5])

In [125]:
np.setxor1d(x,y)

array([-1,  0,  5])

### File Input and Output with Arrays
- NumPy is able to save and load data to and from disk either in text or binary format

In [129]:
arr = np.arange(10)
np.save('some_array', arr) # Saved with .npy extention and in an uncompressed format

In [130]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [141]:
a = np.arange(5)
b = np.arange(10)
c = np.arange(2)
np.savez('three_arrays', a=a, b=b, c=c)

In [142]:
arr = np.load('three_arrays.npz')

In [143]:
arr['c']

array([0, 1])

In [144]:
arr['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [145]:
np.savez_compressed('array_compressed', a=a, b=b, c=c)

### Linear Algebra

In [146]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [147]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [148]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [149]:
x.dot(y) # Method

array([[ 28.,  64.],
       [ 67., 181.]])

In [151]:
np.dot(x,y) #Function

array([[ 28.,  64.],
       [ 67., 181.]])

### Pseudorandom Number Generation

In [157]:
samples = np.random.normal(size=(4, 4))
samples

array([[ 1.04757857,  1.04593826,  0.86371729, -0.12209157],
       [ 0.12471295, -0.32279481,  0.84167471,  2.39096052],
       [ 0.07619959, -0.56644593,  0.03614194, -2.0749776 ],
       [ 0.2477922 , -0.89715678, -0.13679483,  0.01828919]])

In [154]:
np.random.seed(1234)