### Numpy Array - Introduction
- Is fast than the build in python data types
- NumPy internally stores data in a contiguous block of memory, independent of other built-in Python objects. NumPy’s library of algorithms written in the C language can operate on this memory without any type checking or other overhead. NumPy arrays also use much less memory than built-in Python sequences
- NumPy operations perform complex computations on entire arrays without the need for Python for loops

In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [3]:
%time for _ in range(10): my_arr = my_arr * 2

Wall time: 62.5 ms


In [4]:
%time for _ in range(10): my_list2 = [ value * 2 for value in my_list]

Wall time: 1.24 s


### The NumPy ndarray: A Multidimensional Array Object
- An ndarray is a generic multidimensional container for homogeneous data; that is, all of the elements must be the same type

In [5]:
data = np.random.randn(2,3)
data

array([[-0.70890658,  0.8766404 , -1.87441267],
       [ 0.894121  ,  0.75990139, -0.97832951]])

In [6]:
data * 10

array([[ -7.08906579,   8.76640399, -18.74412673],
       [  8.94121005,   7.59901391,  -9.78329515]])

In [7]:
data + data

array([[-1.41781316,  1.7532808 , -3.74882535],
       [ 1.78824201,  1.51980278, -1.95665903]])

In [8]:
data.shape

(2, 3)

In [9]:
data.dtype

dtype('float64')

#### Creating ndarrays

In [10]:
data1 = [1, 2, 3, 4, 5]
my_arr1 = np.array(data1)
my_arr1

array([1, 2, 3, 4, 5])

In [11]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
my_arr2 = np.array(data2)
my_arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
my_arr2.shape

(2, 4)

In [13]:
my_arr2.ndim

2

In [14]:
my_arr3 = np.zeros(5)
my_arr3

array([0., 0., 0., 0., 0.])

In [15]:
my_arr4 = np.ones(5)
my_arr4

array([1., 1., 1., 1., 1.])

In [16]:
np.empty((2, 2, 3)) # 2d array of 2 * 3. empty may return any garbage values not necessary zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [17]:
# arange is a array version of the build in range function
np.arange(5)

array([0, 1, 2, 3, 4])

In [18]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [19]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [20]:
my_arr5 = np.ones((2,2))
my_arr6 = np.zeros_like(my_arr5) # similarly we have ones_like, empty_like, full_like which copies the shape and makes a new array
my_arr6

array([[0., 0.],
       [0., 0.]])

In [21]:
np.full((2,3), '*') # Passing the shape and fill value

array([['*', '*', '*'],
       ['*', '*', '*']], dtype='<U1')

In [22]:
np.eye(2) # 2 * 2 (1's on the diagonal and 0's elsewhere). identity also does the same thing

array([[1., 0.],
       [0., 1.]])

#### Data Types for ndarrays
- The data type or dtype is a special object containing the information (or metadata, data about data)
- int (8,16,32)
- float (16,32,64,128)
- complex(64, 128, 256)
- bool, object, string_, unicode_

In [23]:
my_arr7 = np.array([1, 2, 3, 4, 5], dtype=np.float64)
my_arr7.dtype

dtype('float64')

In [24]:
my_arr8 = np.array(range(10), dtype=np.int32)
my_arr8.dtype

dtype('int32')

In [25]:
# can also cast dtypes
# Calling astype always creates a new array (a copy of the data), even if the new dtype is the same as the old dtype.
my_arr7 = my_arr7.astype(np.int32)

In [26]:
my_arr7.dtype

dtype('int32')

#### Arithmetic with NumPy Arrays
- Arrays are important because they enable you to express batch operations on data without writing any for loops. NumPy users call this vectorization. Any arithmetic operations between equal-size arrays applies the operation element-wise:
- Operations between differently sized arrays is called broadcasting

In [44]:
my_arr9 = np.random.randn(2,2)

In [45]:
my_arr9

array([[ 0.41741516, -0.68029358],
       [ 1.5391361 ,  0.98381221]])

In [46]:
my_arr9 * my_arr9

array([[0.17423542, 0.46279935],
       [2.36893994, 0.96788647]])

In [47]:
my_arr9 - my_arr9

array([[0., 0.],
       [0., 0.]])

In [48]:
my_arr9 + my_arr9

array([[ 0.83483032, -1.36058715],
       [ 3.0782722 ,  1.96762442]])

In [49]:
1 / my_arr9

array([[ 2.3956964 , -1.46995361],
       [ 0.64971512,  1.01645414]])

In [50]:
my_arr9 = my_arr9 ** 2
my_arr9

array([[0.17423542, 0.46279935],
       [2.36893994, 0.96788647]])

In [51]:
my_arr9 ** 0.5

array([[0.41741516, 0.68029358],
       [1.5391361 , 0.98381221]])

In [52]:
my_arr10 = np.random.randn(2,2)
my_arr10 > my_arr9

array([[ True,  True],
       [False, False]])

In [53]:
my_arr10

array([[ 0.66698273,  1.70631623],
       [-1.58552141,  0.7696447 ]])

#### Basic Indexing and Slicing

In [56]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
arr[5]

5

In [58]:
arr[5:8]

array([5, 6, 7])

In [59]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [64]:
arr_slice = arr[5:8] # Does not explicitly copy
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [65]:
arr_copy = arr.copy()
arr_copy

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [67]:
arr_copy[:] = 1 # no effect on original array
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [68]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [69]:
arr2d[0][0]

1

In [71]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [72]:
arr3d[0,0]

array([1, 2, 3])

In [73]:
arr_copy = arr3d.copy()
arr3d[:] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[42, 42, 42],
        [42, 42, 42]]])

In [75]:
arr3d = arr_copy
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

#### Indexing with slices

In [76]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [77]:
arr[:6] # first 6 elements

array([ 0,  1,  2,  3,  4, 64])

In [78]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
arr2d[:2] # first two rows

array([[1, 2, 3],
       [4, 5, 6]])

In [88]:
arr2d[:2][:1]

array([[1, 2, 3]])

In [90]:
arr2d[:2, :2] # first two rows then first 2 colunms

array([[1, 2],
       [4, 5]])

#### Boolean Indexing

In [91]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [92]:
data = np.random.randn(7, 4)
data

array([[ 1.29980858,  1.23395631, -2.4492584 , -0.07226945],
       [ 0.12039535,  0.92830639,  0.15186713,  0.63588957],
       [-0.45602858,  0.53659755, -1.54157113, -0.48133825],
       [-2.2193641 , -0.03904252, -0.55626258,  1.45753699],
       [-0.54480041,  2.33983399,  1.54880118, -0.56771187],
       [-1.68973121, -0.19432546, -0.6247984 ,  1.26716331],
       [-1.41664554,  0.01093219,  0.3558895 , -1.19231393]])

In [93]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [94]:
data[names == 'Bob']

array([[ 1.29980858,  1.23395631, -2.4492584 , -0.07226945],
       [-2.2193641 , -0.03904252, -0.55626258,  1.45753699]])

In [95]:
data[names == 'Bob', :2] # then first two columns

array([[ 1.29980858,  1.23395631],
       [-2.2193641 , -0.03904252]])

In [96]:
mask = (names=='Bob') | (names == 'Will')
data[~mask]

array([[ 0.12039535,  0.92830639,  0.15186713,  0.63588957],
       [-1.68973121, -0.19432546, -0.6247984 ,  1.26716331],
       [-1.41664554,  0.01093219,  0.3558895 , -1.19231393]])

In [97]:
# setting all -ve values to zero
data[data < 0] = 0
data

array([[1.29980858, 1.23395631, 0.        , 0.        ],
       [0.12039535, 0.92830639, 0.15186713, 0.63588957],
       [0.        , 0.53659755, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.45753699],
       [0.        , 2.33983399, 1.54880118, 0.        ],
       [0.        , 0.        , 0.        , 1.26716331],
       [0.        , 0.01093219, 0.3558895 , 0.        ]])

#### Fancy Indexing

In [98]:
arr = np.empty((8, 4))

In [100]:
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [101]:
arr[[0,2,5]]

array([[0., 0., 0., 0.],
       [2., 2., 2., 2.],
       [5., 5., 5., 5.]])

In [102]:
arr = np.arange(32).reshape(8,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [108]:
arr[[0,2]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [113]:
arr[[0,2], [0, -1]] #0th list 1st column, 2rd list last column

array([ 0, 11])

#### Transposing Arrays and Swapping Axes

In [114]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [115]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [118]:
ones2d = np.ones((2,3))
ones2d

array([[1., 1., 1.],
       [1., 1., 1.]])

In [119]:
np.dot(ones2d, ones2d.T)

array([[3., 3.],
       [3., 3.]])

In [122]:
arr = np.arange(6).reshape(2,3)
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [123]:
np.dot(arr, arr.T)

array([[ 5, 14],
       [14, 50]])

In [124]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [125]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [128]:
arr.transpose((2,1,0))

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

### Universal Functions: Fast Element-Wise Array Functions

In [129]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [130]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [131]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [133]:
np.add(arr, arr)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [135]:
np.multiply(arr,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [141]:
arr[-2:] = 100
arr2 = np.arange(1,11)
np.maximum(arr, arr2) # Return the elementwise maximum value

array([  1,   2,   3,   4,   5,   6,   7,   8, 100, 100])

In [142]:
arr = np.random.randn(7) * 5
arr

array([-4.3693577 ,  0.00709581,  5.04561206, -2.29044424, -6.03854005,
       -2.23813239, -2.3762021 ])

In [143]:
remainder, whole_part = np.modf(arr)
remainder, whole_part

(array([-0.3693577 ,  0.00709581,  0.04561206, -0.29044424, -0.03854005,
        -0.23813239, -0.3762021 ]),
 array([-4.,  0.,  5., -2., -6., -2., -2.]))

In [147]:
np.sqrt(arr, arr) # optional 2nd argument as output variable
arr

array([       nan, 0.53873506, 1.22423342,        nan,        nan,
              nan,        nan])

In [160]:
my_list = [1.49, 1.5, 1.51, 1.01]
arr = np.array(my_list)
arr

array([1.49, 1.5 , 1.51, 1.01])

In [161]:
np.ceil(arr)

array([2., 2., 2., 2.])

In [162]:
np.floor(arr)

array([1., 1., 1., 1.])

In [163]:
np.isnan(arr)

array([False, False, False, False])

### Array-Oriented Programming with Arrays

In [173]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [175]:
np.where(cond, xarr, yarr) # if True, pull from xarr else yarr

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [176]:
# Replace all +ve values with 2 and negative with -2
arr = np.random.randn(3,3)
arr

array([[ 0.42085829, -1.9406733 , -0.15979824],
       [-0.6390347 ,  1.68315341,  1.67498022],
       [ 0.88847334,  1.07007575, -0.3613453 ]])

In [177]:
np.where(arr > 0, 2, -2)

array([[ 2, -2, -2],
       [-2,  2,  2],
       [ 2,  2, -2]])

In [178]:
# Set only +ve values to 0 rest asIS
np.where(arr > 0, 0, arr)

array([[ 0.        , -1.9406733 , -0.15979824],
       [-0.6390347 ,  0.        ,  0.        ],
       [ 0.        ,  0.        , -0.3613453 ]])

#### Mathematical and Statistical Methods

In [179]:
arr = np.random.randn(5,4)
arr

array([[ 0.79773559, -0.68066343, -0.46445889,  0.1501953 ],
       [ 1.44349879,  0.50194329,  0.54409242, -0.6261346 ],
       [ 1.91930648,  0.1793611 ,  1.56742864,  1.4227298 ],
       [ 0.17321856,  1.76433503, -0.02557356,  1.13885505],
       [-1.57883272,  0.29849486,  0.14223963,  0.97602758]])

In [180]:
arr.mean() # Entire Array

0.4821899461085114

In [182]:
arr.mean(axis=0) # columnwise mean

array([0.55098534, 0.41269417, 0.35274565, 0.61233463])

In [183]:
arr.mean(axis=1) #rowwise mean

array([-0.04929786,  0.46584998,  1.27220651,  0.76270877, -0.04051766])

In [185]:
arr.std() # Entire array, similarly can be calculated for column and row

0.8917298185366507

In [187]:
np.mean(arr, axis=1) #Alternative way

array([-0.04929786,  0.46584998,  1.27220651,  0.76270877, -0.04051766])

In [188]:
arr.sum()

9.643798922170228

In [189]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [201]:
arr.sum(0)

array([ 9, 12, 15])

In [205]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

In [206]:
arr.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [207]:
arr.cumprod()

array([   1,    2,    6,   24,  120,  720, 5040], dtype=int32)

#### Methods for Boolean Arrays

In [208]:
arr = np.random.randn(100)

In [209]:
# number of +ve values
(arr > 0).sum()

46

In [210]:
# number f -ve values
(arr < 0).sum()

54

In [211]:
bools = np.array([False, False, True, False])
bools.any()

True

In [212]:
bools.all()

False

#### Sorting

In [219]:
arr = np.arange(1,11, 1)
arr[[0, 5, 2]] = 77
arr

array([77,  2, 77,  4,  5, 77,  7,  8,  9, 10])

In [221]:
arr.sort()
arr

array([ 2,  4,  5,  7,  8,  9, 10, 77, 77, 77])

In [222]:
arr = np.random.randn(5, 3)
arr

array([[-0.34141389,  1.7107537 ,  0.78160505],
       [-0.50112265,  1.58274927,  0.50482538],
       [ 0.83497655,  1.32441096,  0.39822441],
       [ 0.03864106,  1.35268731, -0.3743525 ],
       [ 0.44840957,  1.60796457,  1.34513168]])

In [224]:
arr.sort(axis=1) # row level sorting
arr

array([[-0.34141389,  0.78160505,  1.7107537 ],
       [-0.50112265,  0.50482538,  1.58274927],
       [ 0.39822441,  0.83497655,  1.32441096],
       [-0.3743525 ,  0.03864106,  1.35268731],
       [ 0.44840957,  1.34513168,  1.60796457]])

#### Unique and Other Set Logic

In [225]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [229]:
np.unique(names) # Returns sorted and unique value of names. Original array will remain intact

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [230]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

array([1, 2, 3, 4])

In [231]:
# unique is alternative to the below code
sorted(set(names))

['Bob', 'Joe', 'Will']

In [240]:
x = np.array([6, 0, 0, 3, 2, 5, 6])
y = [2, 3, 6, -1]
np.in1d(x,y ) # meaning = x in y

array([ True, False, False,  True,  True, False,  True])

In [241]:
np.intersect1d(x, y)

array([2, 3, 6])

In [242]:
np.union1d(x,y)

array([-1,  0,  2,  3,  5,  6])

In [243]:
np.setdiff1d(x,y)

array([0, 5])

In [244]:
np.setxor1d(x,y)

array([-1,  0,  5])